# numpy session 2

In [3]:
fix_salary=[300,100,50]
variable_salary=[30,20,40]
total=fix_salary+variable_salary
print(total) #this not the result we are looking for

[300, 100, 50, 30, 20, 40]


In [4]:
import numpy as np
fx_sl=np.array(fix_salary)
v_sl=np.array(variable_salary)
now_total=fx_sl+v_sl
print("Total",now_total)  #this is the result is we were looking for

Total [330 120  90]


In [6]:
#Broadcasting
now_total>200   #can peform any math and logical orperation

array([ True, False, False])

In [17]:
#boolean indexing
now_total[now_total>200 ] 

array([330])

## numpy arrays are always homogeneous in nature

In [16]:
#upcasting
print("Result is in Float",np.array([True,3,5.0])+np.array([3,5,False]) ) # #upcasting towrds the biggest one
#String>Float>Int>Boolean

#
np.array([True,'b',5.0])  #all will be in string as the top most is string in between   i.e to <U45

Result is in Float [4. 8. 5.]


array(['True', 'b', '5.0'], dtype='<U5')

In [5]:
from numpy.random import randint as ri
m=ri(1,200,25)
z=m.reshape(5,5)
print('Original matrix\n', z)
print("Sorted according to default axis:\n",np.sort(z))   # defaut axis=1 i.e row-wise sort 
print("Sorted according to column wise\n",np.sort(z, axis=0))    
print("Using quicksot along row\n",np.sort(z, kind="quicksort"))
# kind	      speed	 worstcase	work space	stable
# ‘quicksort’	1	O(n^2)	0	no
# ‘mergesort’	2	O(n*log(n))	~n/2	yes
# ‘heapsort’	3	O(n*log(n))	0	no

Original matrix
 [[180 162  13  25 121]
 [124  76  29  72 187]
 [142  63 145 111 158]
 [ 78   5   1  17  41]
 [ 55 146 112  77 125]]
Sorted according to default axis:
 [[ 13  25 121 162 180]
 [ 29  72  76 124 187]
 [ 63 111 142 145 158]
 [  1   5  17  41  78]
 [ 55  77 112 125 146]]
Sorted according to column wise
 [[ 55   5   1  17  41]
 [ 78  63  13  25 121]
 [124  76  29  72 125]
 [142 146 112  77 158]
 [180 162 145 111 187]]
Using quicksot along row
 [[ 13  25 121 162 180]
 [ 29  72  76 124 187]
 [ 63 111 142 145 158]
 [  1   5  17  41  78]
 [ 55  77 112 125 146]]


In [7]:
print(z[1:3,[1,4]])

[[ 76 187]
 [ 63 158]]


### Subseting

In [17]:
import numpy as np
from numpy.random import randint as ri
m=np.array(ri(10,100,20)).reshape(4,5)
print(m)

[[50 87 52 97 25]
 [39 71 37 81 82]
 [18 59 79 51 62]
 [63 50 43 66 37]]


In [21]:
#boolean operation
#broadcasting
m>50   

array([[False,  True,  True,  True, False],
       [False,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [ True, False, False,  True, False]])

In [22]:
m+50

array([[100, 137, 102, 147,  75],
       [ 89, 121,  87, 131, 132],
       [ 68, 109, 129, 101, 112],
       [113, 100,  93, 116,  87]])

In [23]:
m[m>50]   #>50 from m

array([87, 52, 97, 71, 81, 82, 59, 79, 51, 62, 63, 66])

In [39]:
my_house=np.array([18.0,23.0,34,67])
your_house=np.array([28.0,33.0,14,77])

#logical and / or operations of numpy
print(np.logical_or(my_house>10, your_house<10))
print(np.logical_and(my_house>20, your_house>20))
# can index it also
print(my_house[np.logical_and(my_house>20, your_house>20)])  #it would provide value only Ture places

[ True  True  True  True]
[False  True False  True]
[23. 67.]


In [34]:
#can do like also
print((my_house>10) | (your_house<10))
print((my_house>20) & (your_house>20))


# in python &----and
# &&---is bitwise and

[ True  True  True  True]
[False  True False  True]


In [37]:
for x in np.nditer(m):  #iterate through 2D array
    print(x)

50
87
52
97
25
39
71
37
81
82
18
59
79
51
62
63
50
43
66
37
