# numpy-numerical python

## numpy array

In [3]:
import numpy as np
print(dir(np)) # available function 


['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', 'abs', 'absolute', 'ab

In [4]:
import numpy as np
np.array([1,2,3]) #1D

array([1, 2, 3])

In [7]:
np.array([1.1,2,3]) #1D  #upcasting to float

array([1.1, 2. , 3. ])

In [2]:
import numpy as np
np.array([[1.1,2,3],[2,3,6]]) #2D 

array([[1.1, 2. , 3. ],
       [2. , 3. , 6. ]])

In [3]:
np.array([1,2], ndmin=2)

array([[1, 2]])

In [10]:
np.array([1,2], dtype=complex)

array([1.+0.j, 2.+0.j])

In [22]:
print(np.array([1,2], dtype=[('a','<i4'),('b','<f4')]))  #i4 -32 bit integer and f4----32 bit float


[(1, 1.) (2, 2.)]


In [13]:
#creating an array of sub classes
np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

### Data types

In [7]:
#printing the specification of the matrix
my_mat = [[1,2,3],[4,5,6],[7,8,9]] 
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a mat 
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along 
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [34]:
# getting a vector form a list
l=[1,2,3]

import numpy as np
print(np.asarray(l) is vec) #will return false because it a list rather than array
vec=np.array(l)
print(vec)
print(type(vec))
np.asarray(vec) is vec   # will True a array now

False
[1 2 3]
<class 'numpy.ndarray'>


True

### numpy.asarray

In [36]:
#changing type and checking it
a=np.asarray([1,2], dtype=np.float32)
print(a)

[1. 2.]


In [39]:
np.asarray(a, dtype=np.float32) is a   # will return true

True

In [41]:
np.asarray(a, dtype=np.float64) is a   # will return False

False

In [43]:
issubclass(np.matrix, np.ndarray)    #will return true

True

In [50]:
a=np.matrix([1,2])
print(a)
np.asarray(a) is a #will return false as it is matrix
np.asanyarray(a) is a # will return true as in form of array but not actually array

[[1 2]]


True

### numpy.asanyarray

In [51]:
a=[1,2]
np.asanyarray(a)

array([1, 2])

In [52]:
#numpy.copy

In [77]:
# many ways of copy
a=np.array([1,2,3])
b=np.array(a,copy=True) #copy to b
print('b:',b)
c=a  #copy to c equal to b
print('c:',c)

z=np.copy(a)   #copy c to z
print("z:",z)



b: [1 2 3]
c: [1 2 3]
z: [1 2 3]


In [81]:
#how c and z are different?
#Ans: If we modify a, c changes not z
#example modify a in above and print again

a[0]=10    # i changed one element of the a , a[0] to 10 and c[0] get changed but not z

print(a) #new a
print('c:',c)


print("z:",z)

#menas = create same memory references but copy create same at different location


[10  2  3]
c: [10  2  3]
z: [1 2 3]


## Read data from file
form text or binary
Construct an array from data in a text or binary file.A highly efficient way of reading binary data with a known data-type, as well as parsing simply formatted text files. Data written using the tofile method can be read using this function.

In [1]:
#reading csv
import os
import numpy as np
np.fromfile('E:/PHD/PML/PML with jupyter notebook/excercise/day5/example_csv/first.csv')

array([2.10883413e+214, 6.10358018e+257, 7.63594962e+218, 1.50008929e+248,
       8.16992705e-096, 5.79980165e+063, 5.12676886e+160, 9.22930854e+242,
       3.77663042e+209, 1.17522874e+214, 3.03667981e-152, 3.68162108e+194,
       4.94545444e-096, 4.44003412e+078, 9.17549014e-072, 1.63402450e+078,
       1.71878595e+161, 5.03404042e+223, 9.29450074e+242, 1.47292513e-052,
       9.46242257e-096, 3.42657989e-062, 1.31196978e-071, 3.70087202e-245,
       7.70751235e-043, 3.49895589e+194, 2.67451579e+092, 1.17822703e+180,
       2.21062911e-052, 2.24564091e-057, 8.99242616e-096, 1.17941667e-095,
       1.08394078e-042, 8.91356708e-096, 1.39838987e-076, 5.84871770e+199,
       6.52864328e-095, 1.37682942e-094, 1.19832989e-071, 9.64361265e-048,
       4.66063686e-062, 1.08651111e-095, 2.96620182e-260, 1.31262871e-071,
       1.74785577e-152, 6.37105500e+160, 3.51288501e+257, 2.24750538e-057,
       7.58792333e-096, 1.65395713e-047, 3.69161467e-057, 3.67204023e-062,
       1.17500274e-047, 2

In [9]:
#reading text file
np.fromfile('E:\PHD\PML\PML with jupyter notebook\excercise\day5\data.txt')

array([3.68777819e+180, 2.11833428e+161, 2.88833485e+170, 7.30567486e+265,
       1.16097023e-028, 1.92526839e+161, 1.38497705e+219, 3.48410114e-081,
       8.02496125e+165, 3.91667200e-109, 1.38760004e+219, 9.81303597e+242,
       1.06239611e-153, 1.16096346e-028, 1.30424638e-142, 9.27360560e+199,
       4.38413982e+228, 1.38497705e+219, 3.48410114e-081, 3.44620186e-085,
       2.59027849e-144, 2.59903826e-144, 5.03285799e+223, 2.11833403e+161,
       2.40797627e+199, 9.88885241e+165, 2.59903818e-144, 3.63515802e+228,
       3.32304084e-027, 3.44622396e-085, 2.59027849e-144, 2.59903826e-144,
       4.46602715e-143])

In [40]:
# To save the data
#np.save('C:/Datasets/College_Data', x)
x=np.array([1,2,5], dtype=np.int32)
np.save('1.txt', x)



OSError: [Errno 22] Invalid argument: '1.txt.npy'

In [42]:
#read this file
print(np.load('1.txt.npy','r'))

np.fromfile('1.txt.npy')

[1 2 3]


array([1.87585069e-309, 1.17119999e+171, 3.21613038e-056, 8.44740097e+252,
       2.65141232e+180, 9.92152605e+247, 2.16209968e+233, 2.34519039e-110,
       6.01347003e-154, 6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
       6.01347002e-154, 6.01347002e-154, 6.01347002e-154, 6.55490914e-260,
       4.24399158e-314])

In [41]:
#numpy.fromfunction

In [45]:
#lambda function

In [49]:
import numpy as np
np.fromfunction(lambda i,j:i==j, (3,3), dtype=np.int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [51]:
np.fromfunction(lambda i,j:i<j,(3,3), dtype=int)

array([[False,  True,  True],
       [False, False,  True],
       [False, False, False]])

In [53]:
np.fromfunction(lambda i,j:i+j,(3,3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [4]:
#creating 1-D array by iterable object
import numpy as np
iterable=(x*x for x in range(5))
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [5]:
#Create a new 1 dimensional array from an iterable object.
iterable=( x*(x-1)for x in range(8))
np.fromiter(iterable,float)

array([ 0.,  0.,  2.,  6., 12., 20., 30., 42.])

In [15]:
#from a string
print(np.fromstring('1 2', dtype=int, sep=' '))   #convert to 1-D array from sting and pick type is int only
print(np.fromstring('1 aman', dtype=int, sep=' '))  #will return only the int item and covert to array
print(np.fromstring('kumar aman', dtype=int, sep=' '))  #will return empty


[1 2]
[1]
[]


### The assignment 6 question

In [73]:
#Write a function so that the columns of the output matrix are powers of the input vector.
#try -1
l=[1,2,3]

power1=list(x*x for x in l)
print(power1)
vec=np.array(power1)
print(vec)
np.fromiter(vec, int)

[1, 4, 9]
[1 4 9]


array([1, 4, 9])

In [2]:
#try -2
np.fromfunction(lambda i,j:(i+j)**2,(4,4), dtype=int)

NameError: name 'np' is not defined

### Assignment question

In [16]:
# Correct solution
input_vec=np.array([1,2,3,4,5])
print(input_vec)
cols=8
np.column_stack([input_vec**(cols-1-i) for i in range(cols)])

[1 2 3 4 5]


array([[    1,     1,     1,     1,     1,     1,     1,     1],
       [  128,    64,    32,    16,     8,     4,     2,     1],
       [ 2187,   729,   243,    81,    27,     9,     3,     1],
       [16384,  4096,  1024,   256,    64,    16,     4,     1],
       [78125, 15625,  3125,   625,   125,    25,     5,     1]],
      dtype=int32)

### Load data from text

In [27]:
#StringIO
from io import StringIO
c=StringIO('0 1\n2 3')
print(c)

print(np.genfromtxt(c) )  # to generate array from string

#or
#print(np.loadtxt(c) )

[[0. 1.]
 [2. 3.]]


In [28]:
#more example
d= StringIO("M 21 72\nF 35 58" )
np.genfromtxt(d)   #bacause the data is not same type so it will put nan in place of string type data 

array([[nan, 21., 72.],
       [nan, 35., 58.]])

In [31]:
#for the above type of conversiton we need to define our data type
np.genfromtxt(d, dtype={'names': ('gender', 'age', 'weight'), 'formats': ('S1', 'i4', 'f4')})

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x0000000005C0C678>"
  


array([], dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<f4')])

In [38]:
c = StringIO ( "1,0,2\n3,0,4" )

x, y = np.loadtxt(c, delimiter=',', usecols=(0, 2),) #it will skip the 1 cols means 0 in data
print(x)
print(y)

[1. 2.]
[3. 4.]


In [12]:
#creating a record from list of flat arrays
import numpy as np
x1=np.array([1,2,3,4])
x2=np.array([3,'abc',5,6])
x3=np.array([1.2,2,3,4])
r=np.core.records.fromarrays([x1,x2,x3], names='a,b,c')
print(r)
np.matrix(r) #here r is the record of all above three arrays

[(1, '3', 1.2) (2, 'abc', 2. ) (3, '5', 3. ) (4, '6', 4. )]


matrix([[(1, '3', 1.2), (2, 'abc', 2. ), (3, '5', 3. ), (4, '6', 4. )]],
       dtype=(numpy.record, [('a', '<i4'), ('b', '<U11'), ('c', '<f8')]))

### arrange and lines

In [15]:
#np.arrange()
np.arange(20,40)# A series of numbers from low to high

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [22]:
np.arange(20,40,5)# A series of numbers from low to high with third place given difference
np.arange(20,40,.5)# A series of numbers from low to high

array([20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. ,
       25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5,
       31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5, 35. , 35.5, 36. ,
       36.5, 37. , 37.5, 38. , 38.5, 39. , 39.5])

In [27]:
#more
print("reverse order with gap")
np.arange(50,-5,-5)

reverse order with gap


array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [85]:
np.linspace(1,5,23) # total #23 liner spaced numbers between 

array([1.        , 1.18181818, 1.36363636, 1.54545455, 1.72727273,
       1.90909091, 2.09090909, 2.27272727, 2.45454545, 2.63636364,
       2.81818182, 3.        , 3.18181818, 3.36363636, 3.54545455,
       3.72727273, 3.90909091, 4.09090909, 4.27272727, 4.45454545,
       4.63636364, 4.81818182, 5.        ])

In [88]:
np.linspace(2,3, num=6) #can be written as

array([2. , 2.2, 2.4, 2.6, 2.8, 3. ])

In [91]:
np.linspace(2,3, num=6, endpoint=False) # it will remove the end point

array([2.        , 2.16666667, 2.33333333, 2.5       , 2.66666667,
       2.83333333])

In [93]:
np.linspace(2,3, num=6, retstep=True) #Will show you the step size also i.e interval

(array([2. , 2.2, 2.4, 2.6, 2.8, 3. ]), 0.2)

In [94]:
#Return numbers spaced evenly on a log scale.
np.logspace(2.0,3.0,num=4)  # we acn use endpoint and other option here also

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [95]:
np.logspace(2.0,3.0,num=4, base=2) #on base 2

array([4.        , 5.0396842 , 6.34960421, 8.        ])

### Matrix creation

In [30]:
print('Vector of Zeros')
np.zeros(10)

Vector of Zeros


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
print('Matrix of zeros')
print(np.zeros((3,4), dtype=int))
np.zeros((3,4))

Matrix of zeros
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
print('matrix of ones')

np.ones((2,3))   #can be of given type also by dtype=type


matrix of ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [84]:
#empty 
np.empty((3,5))
np.empty((4,3)) # to be disscuss

array([[0.48430232, 0.92511232, 0.56757603],
       [0.78706669, 0.63849107, 0.60687894],
       [0.77775758, 0.757541  , 0.3149716 ],
       [0.21070154, 0.5565172 , 0.65070069]])

In [43]:
#identity amtrix
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
#Create a two-dimensional array with the flattened input as a diagonal.
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Random number generation

In [51]:
np.random.rand(3) #will generate an array of random number
#matrix of random no.
np.random.rand(4,3)    # will pic number from uniform distribution 

#will always provide value between 0 to 1

array([[0.48430232, 0.92511232, 0.56757603],
       [0.78706669, 0.63849107, 0.60687894],
       [0.77775758, 0.757541  , 0.3149716 ],
       [0.21070154, 0.5565172 , 0.65070069]])

In [54]:
##Numbers from Normal distribution with zero mean and standard deviation 1 i.e. from bell curv
np.random.randn(4) #the vector
np.random.randn(4,5) #the matrix

# will give value from bell curv and provide negative value also

array([[ 1.25344284, -1.08279715,  0.84551495,  0.26132209,  1.37359701],
       [ 1.1142949 ,  1.31706471, -0.18229675, -0.20245303, -0.0677896 ],
       [ 1.1711004 ,  1.9643378 , -0.74776247, -0.36741738, -0.5614014 ],
       [-1.16845773,  0.19438613,  0.49441323, -1.01064357, -0.27001199]])

In [59]:
print(5*np.random.randn(4)) #can do multifly

[-6.72570056  3.72265936  6.66873621 -0.08545981]


In [76]:
#Random integer vector : randint (low, high, # of samples to be drawn)
np.random.randint(1,100,50)


array([38, 79, 12, 88, 59, 97, 77, 49, 10, 36, 53, 79, 98, 78, 16, 63, 30,
        6,  6, 54, 60, 12,  4, 88, 12, 19, 95, 29, 30, 26, 55, 84, 15, 84,
       58, 98, 94, 66, 61, 82,  4, 57, 36, 43,  2, 78, 35, 20, 47, 54])

In [78]:
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn


20 samples drawn from a dice throw: [3 4 1 6 4 6 3 6 2 4 3 6 3 4 2 1 5 4 1 2]


### Reshapping 

In [166]:
from numpy.random import randint as ri
a=ri(3,400,20)
print("a:",a)
print("Shape of a:",a.shape)

a: [ 15  54 291 119  40 255 282 191 218 299 335 138 318  53  18 319 196 291
 331  47]
Shape of a: (20,)


In [167]:
b=a.reshape(4,5)
print("After Reshape:\n",b)

After Reshape:
 [[ 15  54 291 119  40]
 [255 282 191 218 299]
 [335 138 318  53  18]
 [319 196 291 331  47]]


In [170]:
# we can reshape in chunks also
a.reshape(2,2,5)    #will return 2 matrix of (2,5)

array([[[ 15,  54, 291, 119,  40],
        [255, 282, 191, 218, 299]],

       [[335, 138, 318,  53,  18],
        [319, 196, 291, 331,  47]]])

In [122]:
m=ri(1,100,25).reshape(5,5)
print(m)
# sort the above matrix
np.sort(m)

[[24 31 51 17 99]
 [63 14 67 53 13]
 [24 82 78 61 36]
 [86 87 13 31 19]
 [17 17 85 77 96]]


array([[17, 24, 31, 51, 99],
       [13, 14, 53, 63, 67],
       [24, 36, 61, 78, 82],
       [13, 19, 31, 86, 87],
       [17, 17, 77, 85, 96]])

In [128]:
a=np.arange(9)
print(a)
print(a.reshape(3,3))
np.sort(a.reshape(3,3))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
z=np.diag(a) #in vec it put vector values on diagonal
print(z)

[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 5 0 0 0]
 [0 0 0 0 0 0 6 0 0]
 [0 0 0 0 0 0 0 7 0]
 [0 0 0 0 0 0 0 0 8]]


In [133]:
np.diag(z) #but in matrix it will return the diagnal

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [138]:
#exmaple over diag
l=[[2,3,4],[3,4,5],[5,6,7]]
m=np.matrix(l)
print(m)

[[2 3 4]
 [3 4 5]
 [5 6 7]]


In [140]:
np.diag(m) #will return dialnal elements vector

array([2, 4, 7])

In [142]:
np.diag(m, k=1)  # the upper diagnal

array([3, 5])

In [147]:
np.diag(m, k=-1) #lower , k=2 the upper most and k=-2 the lower most

array([3, 6])

In [150]:
np.diag(np.diag(m))  #again put diagnal vector in a matrix with these value in diagnal

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 7]])

In [153]:
np.diag([1,2],1) # last 1 told the position ---that equal to k=1


array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [154]:
#many other diagnals

In [159]:
np.tri(3,5,0, dtype=int)


array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [161]:
np.tri(3,5,1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [163]:
np.tri(3,5,2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

### Indexing and slicing

In [173]:
arr=np.arange(0,11)
print('Array:',arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [179]:
print('Element at 7th index:',arr[7])
print(arr[1:4])# values from idex 1 to 4

Element at 7th index: 7
[1 2 3]


In [186]:
print(arr[-1::-1])  #reverse through slicing

[10  9  8  7  6  5  4  3  2  1  0]


In [187]:
#last thee elements
print(arr[-1:-6:-2])   #last three with gap of two

[10  8  6]


In [196]:
#slicing
m=np.array([[11,22,33],[33,55,66],[67,87,57]])
print("original matrix:\n",m)

#now slice the matrix
m_slice=m[:2,:2]
print('Sliced matrix:\n',m_slice)

original matrix:
 [[11 22 33]
 [33 55 66]
 [67 87 57]]
Sliced matrix:
 [[11 22]
 [33 55]]


In [198]:
m_slice=m[:-2,:-2]
print('Sliced matrix:\n',m_slice)

Sliced matrix:
 [[11]]


In [205]:
m1=m[m>50]  #will make new matrix wit elements of >50 from original m
print("new m:",m1)

new m: [55 66 67 87 57]


In [207]:
#return row or column only
print(m[2]) # entrire 2nd row means 3rd as first is at index 0 

[67 87 57]


In [210]:
print(m[:,2]) # entrire 2nd column means 3rd as first is at index 0 

[33 66 57]


In [221]:
#sub set matricies
print(m[1:3, 2:5])

[[66]
 [57]]


### Universal Functions

In [2]:
import  numpy as np
m1=np.arange(0,24).reshape(4,6)
print(m1)
m2=np.arange(24,48).reshape(4,6)
print(m2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]


In [231]:
m3=m1+m2
print(m3)

[[24 26 28 30 32 34]
 [36 38 40 42 44 46]
 [48 50 52 54 56 58]
 [60 62 64 66 68 70]]


In [3]:
m4=m1*m2
print(m4)

[[   0   25   52   81  112  145]
 [ 180  217  256  297  340  385]
 [ 432  481  532  585  640  697]
 [ 756  817  880  945 1012 1081]]


In [4]:
#exponential e(2.71)
print(np.exp(m4))  #will provide the exponential matrix (e**element) of each element 

[[1.00000000e+000 7.20048993e+010 3.83100800e+022 1.50609731e+035
  4.37503945e+048 9.39074129e+062]
 [1.48938420e+078 1.74543055e+094 1.51142767e+111 9.67077157e+128
  4.57218555e+147 1.59725969e+167]
 [4.12302703e+187 7.86404148e+208 1.10831796e+231 1.15417567e+254
  8.88113390e+277 5.04956406e+302]
 [            inf             inf             inf             inf
              inf             inf]]


In [235]:
print(m1/m2)

[[0.         0.04       0.07692308 0.11111111 0.14285714 0.17241379]
 [0.2        0.22580645 0.25       0.27272727 0.29411765 0.31428571]
 [0.33333333 0.35135135 0.36842105 0.38461538 0.4        0.41463415]
 [0.42857143 0.44186047 0.45454545 0.46666667 0.47826087 0.4893617 ]]


In [5]:
print(m2-m1)

[[24 24 24 24 24 24]
 [24 24 24 24 24 24]
 [24 24 24 24 24 24]
 [24 24 24 24 24 24]]


In [30]:
np.sum(m4) #sum of all elements of a matrix

10948

### some basic stats

In [11]:
np.sum(m4, axis=0) #sum of all corresponding columns are  zero'th row

array([1368, 1540, 1720, 1908, 2104, 2308])

In [12]:
np.sum(m4, axis=1) #sum of each corresponding row at position column first

array([ 415, 1675, 3367, 5491])

In [21]:
new=np.array([[1,2,3],[4,5,6]])
print(new)
np.prod(new, axis=0) #product similarly

[[1 2 3]
 [4 5 6]]


array([ 4, 10, 18])

In [26]:
print(np.sum(new))
np.mean(new) #finding mean


21


3.5

In [27]:
print(np.median(new))

3.5


In [28]:
print(np.std(new)) #standard deviation

1.707825127659933


In [31]:
print(np.var(new)) #variance of elemnts of the matrix

2.9166666666666665


In [34]:
#percentile
print('50 percentile:',np.percentile(new,50))
print('90 percentile:',np.percentile(new,90))

50 percentile: 3.5
50 percentile: 5.5


### Broadcasting

In [239]:
print(m1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [243]:
add_row=np.array([1,1,1,1,1,1])
print(add_row)

[1 1 1 1 1 1]


In [1]:
#broadcasting
print(m1+add_row)   # adding add_row to all rows of m1

NameError: name 'm1' is not defined

In [8]:
import numpy as np
a=np.array([[1,2,3]])
b=np.array([[1],[2],[3]])
print(np.shape(a))
print(np.shape(b))
new_arr=[np.array(x) for x in np.broadcast_arrays(a,b)]
print(new_arr)

# more specific
for ar in new_arr:
    print(ar)    # broadcast always works towards major dimention hence b=3*1 and a= 1*3   final product would be 3*3 for both row major and column major

(1, 3)
(3, 1)
[array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]), array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


### Array math
performing math on arrays